// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/faz.proto

package faz

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Associates this type of event with the given function for future execution by Faz.
type HookRequest struct {
	// An arbitrary int that is unique to this type of event
	EventType int32 `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// A string known to Faz that represents a function that can process an event of type `event_type`
	EventFunction        string   `protobuf:"bytes,2,opt,name=event_function,json=eventFunction,proto3" json:"event_function,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HookRequest) Reset()         { *m = HookRequest{} }
func (m *HookRequest) String() string { return proto.CompactTextString(m) }
func (*HookRequest) ProtoMessage()    {}
func (*HookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89695b1e0eb96189, []int{0}
}

func (m *HookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HookRequest.Unmarshal(m, b)
}
func (m *HookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HookRequest.Marshal(b, m, deterministic)
}
func (m *HookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HookRequest.Merge(m, src)
}
func (m *HookRequest) XXX_Size() int {
	return xxx_messageInfo_HookRequest.Size(m)
}
func (m *HookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HookRequest proto.InternalMessageInfo

func (m *HookRequest) GetEventType() int32 {
	if m != nil {
		return m.EventType
	}
	return 0
}

func (m *HookRequest) GetEventFunction() string {
	if m != nil {
		return m.EventFunction
	}
	return ""
}

type HookReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HookReply) Reset()         { *m = HookReply{} }
func (m *HookReply) String() string { return proto.CompactTextString(m) }
func (*HookReply) ProtoMessage()    {}
func (*HookReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_89695b1e0eb96189, []int{1}
}

func (m *HookReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HookReply.Unmarshal(m, b)
}
func (m *HookReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HookReply.Marshal(b, m, deterministic)
}
func (m *HookReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HookReply.Merge(m, src)
}
func (m *HookReply) XXX_Size() int {
	return xxx_messageInfo_HookReply.Size(m)
}
func (m *HookReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HookReply.DiscardUnknown(m)
}

var xxx_messageInfo_HookReply proto.InternalMessageInfo

// Unregisters an event of the given type, if registered.  Has no effect if already unregistered.
type UnhookRequest struct {
	EventType            int32    `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnhookRequest) Reset()         { *m = UnhookRequest{} }
func (m *UnhookRequest) String() string { return proto.CompactTextString(m) }
func (*UnhookRequest) ProtoMessage()    {}
func (*UnhookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89695b1e0eb96189, []int{2}
}

func (m *UnhookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnhookRequest.Unmarshal(m, b)
}
func (m *UnhookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnhookRequest.Marshal(b, m, deterministic)
}
func (m *UnhookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnhookRequest.Merge(m, src)
}
func (m *UnhookRequest) XXX_Size() int {
	return xxx_messageInfo_UnhookRequest.Size(m)
}
func (m *UnhookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnhookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnhookRequest proto.InternalMessageInfo

func (m *UnhookRequest) GetEventType() int32 {
	if m != nil {
		return m.EventType
	}
	return 0
}

type UnhookReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnhookReply) Reset()         { *m = UnhookReply{} }
func (m *UnhookReply) String() string { return proto.CompactTextString(m) }
func (*UnhookReply) ProtoMessage()    {}
func (*UnhookReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_89695b1e0eb96189, []int{3}
}

func (m *UnhookReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnhookReply.Unmarshal(m, b)
}
func (m *UnhookReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnhookReply.Marshal(b, m, deterministic)
}
func (m *UnhookReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnhookReply.Merge(m, src)
}
func (m *UnhookReply) XXX_Size() int {
	return xxx_messageInfo_UnhookReply.Size(m)
}
func (m *UnhookReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnhookReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnhookReply proto.InternalMessageInfo

// Represents an arriving event of the given type with an arbitrary message payload.
type EventRequest struct {
	EventType            int32    `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload              *any.Any `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_89695b1e0eb96189, []int{4}
}

func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (m *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(m, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetEventType() int32 {
	if m != nil {
		return m.EventType
	}
	return 0
}

func (m *EventRequest) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Represents an arbitrary message reply payload, if the event was not in error.
type EventReply struct {
	Payload              *any.Any `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventReply) Reset()         { *m = EventReply{} }
func (m *EventReply) String() string { return proto.CompactTextString(m) }
func (*EventReply) ProtoMessage()    {}
func (*EventReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_89695b1e0eb96189, []int{5}
}

func (m *EventReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventReply.Unmarshal(m, b)
}
func (m *EventReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventReply.Marshal(b, m, deterministic)
}
func (m *EventReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventReply.Merge(m, src)
}
func (m *EventReply) XXX_Size() int {
	return xxx_messageInfo_EventReply.Size(m)
}
func (m *EventReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EventReply.DiscardUnknown(m)
}

var xxx_messageInfo_EventReply proto.InternalMessageInfo

func (m *EventReply) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*HookRequest)(nil), "faz.HookRequest")
	proto.RegisterType((*HookReply)(nil), "faz.HookReply")
	proto.RegisterType((*UnhookRequest)(nil), "faz.UnhookRequest")
	proto.RegisterType((*UnhookReply)(nil), "faz.UnhookReply")
	proto.RegisterType((*EventRequest)(nil), "faz.EventRequest")
	proto.RegisterType((*EventReply)(nil), "faz.EventReply")
}

func init() { proto.RegisterFile("protos/faz.proto", fileDescriptor_89695b1e0eb96189) }

var fileDescriptor_89695b1e0eb96189 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xff, 0xfd, 0xeb, 0x26, 0xbb, 0x75, 0x73, 0x06, 0x1f, 0x66, 0x41, 0x18, 0x05, 0x61,
	0x08, 0xa6, 0xb2, 0xe9, 0xc3, 0xc0, 0x17, 0x05, 0x87, 0xcf, 0x9d, 0xbe, 0x08, 0x52, 0xd2, 0x9a,
	0x76, 0xc5, 0x9a, 0xc4, 0x35, 0x1d, 0xa4, 0xdf, 0xc4, 0x6f, 0x2b, 0x4d, 0x5a, 0xec, 0xde, 0xfa,
	0x96, 0xfe, 0xce, 0x3d, 0xe9, 0x3d, 0x37, 0x17, 0xc6, 0x62, 0xcb, 0x25, 0xcf, 0xbd, 0x98, 0x94,
	0x58, 0x1f, 0xd1, 0x41, 0x4c, 0x4a, 0xe7, 0x3c, 0xe1, 0x3c, 0xc9, 0xa8, 0xa7, 0x51, 0x58, 0xc4,
	0x1e, 0x61, 0xca, 0xe8, 0xee, 0x1a, 0xec, 0x67, 0xce, 0x3f, 0x7d, 0xfa, 0x5d, 0xd0, 0x5c, 0xa2,
	0x0b, 0x00, 0xba, 0xa3, 0x4c, 0x06, 0x52, 0x09, 0x3a, 0xb1, 0xa6, 0xd6, 0xac, 0xe7, 0x0f, 0x34,
	0x79, 0x51, 0x82, 0xa2, 0x4b, 0x18, 0x19, 0x39, 0x2e, 0x58, 0x24, 0x53, 0xce, 0x26, 0xff, 0xa7,
	0xd6, 0x6c, 0xe0, 0x0f, 0x35, 0x5d, 0xd5, 0xd0, 0xb5, 0x61, 0x60, 0x2e, 0x15, 0x99, 0x72, 0x31,
	0x0c, 0x5f, 0xd9, 0xa6, 0xf3, 0x3f, 0xdc, 0x21, 0xd8, 0x4d, 0x7d, 0x65, 0x7f, 0x87, 0xe3, 0xa7,
	0x4a, 0xeb, 0xd8, 0x21, 0x86, 0x23, 0x41, 0x54, 0xc6, 0xc9, 0x87, 0x6e, 0xcd, 0x9e, 0x9f, 0x61,
	0x13, 0x1e, 0x37, 0xe1, 0xf1, 0x03, 0x53, 0x7e, 0x53, 0xe4, 0xde, 0x03, 0xd4, 0xd7, 0x8b, 0x4c,
	0xb5, 0xdd, 0x56, 0x07, 0xf7, 0xfc, 0xc7, 0x02, 0x58, 0x91, 0x72, 0x4d, 0xb7, 0xbb, 0x34, 0xa2,
	0xe8, 0x0a, 0x0e, 0xab, 0xc6, 0xd1, 0x18, 0x57, 0x0f, 0xd0, 0x9a, 0xab, 0x33, 0x6a, 0x91, 0x2a,
	0xd5, 0x3f, 0x74, 0x03, 0xfd, 0x42, 0xc7, 0x44, 0x48, 0x6b, 0x7b, 0x33, 0x72, 0xc6, 0x7b, 0xcc,
	0x38, 0xae, 0xa1, 0xa7, 0x73, 0xa2, 0x53, 0x2d, 0xb6, 0xa7, 0xe2, 0x9c, 0xb4, 0x91, 0x2e, 0x7f,
	0xbc, 0x7b, 0x5b, 0x24, 0xa9, 0xdc, 0x14, 0x21, 0x8e, 0xf8, 0x97, 0x17, 0x67, 0x9c, 0x30, 0x2f,
	0xca, 0xa3, 0xf4, 0x76, 0xb9, 0x0c, 0xcc, 0x57, 0xbd, 0x2c, 0x09, 0x0f, 0xfe, 0xd6, 0x26, 0xec,
	0xeb, 0xf3, 0xe2, 0x37, 0x00, 0x00, 0xff, 0xff, 0xae, 0x1d, 0x11, 0xe5, 0x4b, 0x02, 0x00, 0x00,
}
