// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/caw.proto

package caw

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Time as given by Linux gettimeofday().
type Timestamp struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Useconds             int64    `protobuf:"varint,2,opt,name=useconds,proto3" json:"useconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_335e7fb6a870bb35, []int{0}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetUseconds() int64 {
	if m != nil {
		return m.Useconds
	}
	return 0
}

type Caw struct {
	Username             string     `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Text                 string     `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Id                   []byte     `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	ParentId             []byte     `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Timestamp            *Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Caw) Reset()         { *m = Caw{} }
func (m *Caw) String() string { return proto.CompactTextString(m) }
func (*Caw) ProtoMessage()    {}
func (*Caw) Descriptor() ([]byte, []int) {
	return fileDescriptor_335e7fb6a870bb35, []int{1}
}

func (m *Caw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Caw.Unmarshal(m, b)
}
func (m *Caw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Caw.Marshal(b, m, deterministic)
}
func (m *Caw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Caw.Merge(m, src)
}
func (m *Caw) XXX_Size() int {
	return xxx_messageInfo_Caw.Size(m)
}
func (m *Caw) XXX_DiscardUnknown() {
	xxx_messageInfo_Caw.DiscardUnknown(m)
}

var xxx_messageInfo_Caw proto.InternalMessageInfo

func (m *Caw) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Caw) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Caw) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Caw) GetParentId() []byte {
	if m != nil {
		return m.ParentId
	}
	return nil
}

func (m *Caw) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type RegisteruserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisteruserRequest) Reset()         { *m = RegisteruserRequest{} }
func (m *RegisteruserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisteruserRequest) ProtoMessage()    {}
func (*RegisteruserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_335e7fb6a870bb35, []int{2}
}

func (m *RegisteruserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteruserRequest.Unmarshal(m, b)
}
func (m *RegisteruserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteruserRequest.Marshal(b, m, deterministic)
}
func (m *RegisteruserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteruserRequest.Merge(m, src)
}
func (m *RegisteruserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisteruserRequest.Size(m)
}
func (m *RegisteruserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteruserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteruserRequest proto.InternalMessageInfo

func (m *RegisteruserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type RegisteruserReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisteruserReply) Reset()         { *m = RegisteruserReply{} }
func (m *RegisteruserReply) String() string { return proto.CompactTextString(m) }
func (*RegisteruserReply) ProtoMessage()    {}
func (*RegisteruserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_335e7fb6a870bb35, []int{3}
}

func (m *RegisteruserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteruserReply.Unmarshal(m, b)
}
func (m *RegisteruserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteruserReply.Marshal(b, m, deterministic)
}
func (m *RegisteruserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteruserReply.Merge(m, src)
}
func (m *RegisteruserReply) XXX_Size() int {
	return xxx_messageInfo_RegisteruserReply.Size(m)
}
func (m *RegisteruserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteruserReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteruserReply proto.InternalMessageInfo

type CawRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ParentId             []byte   `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CawRequest) Reset()         { *m = CawRequest{} }
func (m *CawRequest) String() string { return proto.CompactTextString(m) }
func (*CawRequest) ProtoMessage()    {}
func (*CawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_335e7fb6a870bb35, []int{4}
}

func (m *CawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CawRequest.Unmarshal(m, b)
}
func (m *CawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CawRequest.Marshal(b, m, deterministic)
}
func (m *CawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CawRequest.Merge(m, src)
}
func (m *CawRequest) XXX_Size() int {
	return xxx_messageInfo_CawRequest.Size(m)
}
func (m *CawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CawRequest proto.InternalMessageInfo

func (m *CawRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CawRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CawRequest) GetParentId() []byte {
	if m != nil {
		return m.ParentId
	}
	return nil
}

type CawReply struct {
	Caw                  *Caw     `protobuf:"bytes,1,opt,name=caw,proto3" json:"caw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CawReply) Reset()         { *m = CawReply{} }
func (m *CawReply) String() string { return proto.CompactTextString(m) }
func (*CawReply) ProtoMessage()    {}
func (*CawReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_335e7fb6a870bb35, []int{5}
}

func (m *CawReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CawReply.Unmarshal(m, b)
}
func (m *CawReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CawReply.Marshal(b, m, deterministic)
}
func (m *CawReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CawReply.Merge(m, src)
}
func (m *CawReply) XXX_Size() int {
	return xxx_messageInfo_CawReply.Size(m)
}
func (m *CawReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CawReply.DiscardUnknown(m)
}

var xxx_messageInfo_CawReply proto.InternalMessageInfo

func (m *CawReply) GetCaw() *Caw {
	if m != nil {
		return m.Caw
	}
	return nil
}

type FollowRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ToFollow             string   `protobuf:"bytes,2,opt,name=to_follow,json=toFollow,proto3" json:"to_follow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowRequest) Reset()         { *m = FollowRequest{} }
func (m *FollowRequest) String() string { return proto.CompactTextString(m) }
func (*FollowRequest) ProtoMessage()    {}
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_335e7fb6a870bb35, []int{6}
}

func (m *FollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowRequest.Unmarshal(m, b)
}
func (m *FollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowRequest.Marshal(b, m, deterministic)
}
func (m *FollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowRequest.Merge(m, src)
}
func (m *FollowRequest) XXX_Size() int {
	return xxx_messageInfo_FollowRequest.Size(m)
}
func (m *FollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowRequest proto.InternalMessageInfo

func (m *FollowRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FollowRequest) GetToFollow() string {
	if m != nil {
		return m.ToFollow
	}
	return ""
}

type FollowReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowReply) Reset()         { *m = FollowReply{} }
func (m *FollowReply) String() string { return proto.CompactTextString(m) }
func (*FollowReply) ProtoMessage()    {}
func (*FollowReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_335e7fb6a870bb35, []int{7}
}

func (m *FollowReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowReply.Unmarshal(m, b)
}
func (m *FollowReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowReply.Marshal(b, m, deterministic)
}
func (m *FollowReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowReply.Merge(m, src)
}
func (m *FollowReply) XXX_Size() int {
	return xxx_messageInfo_FollowReply.Size(m)
}
func (m *FollowReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowReply.DiscardUnknown(m)
}

var xxx_messageInfo_FollowReply proto.InternalMessageInfo

type ReadRequest struct {
	CawId                []byte   `protobuf:"bytes,1,opt,name=caw_id,json=cawId,proto3" json:"caw_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_335e7fb6a870bb35, []int{8}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetCawId() []byte {
	if m != nil {
		return m.CawId
	}
	return nil
}

type ReadReply struct {
	Caws                 []*Caw   `protobuf:"bytes,1,rep,name=caws,proto3" json:"caws,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadReply) Reset()         { *m = ReadReply{} }
func (m *ReadReply) String() string { return proto.CompactTextString(m) }
func (*ReadReply) ProtoMessage()    {}
func (*ReadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_335e7fb6a870bb35, []int{9}
}

func (m *ReadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReply.Unmarshal(m, b)
}
func (m *ReadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReply.Marshal(b, m, deterministic)
}
func (m *ReadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReply.Merge(m, src)
}
func (m *ReadReply) XXX_Size() int {
	return xxx_messageInfo_ReadReply.Size(m)
}
func (m *ReadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReply proto.InternalMessageInfo

func (m *ReadReply) GetCaws() []*Caw {
	if m != nil {
		return m.Caws
	}
	return nil
}

type ProfileRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileRequest) Reset()         { *m = ProfileRequest{} }
func (m *ProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileRequest) ProtoMessage()    {}
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_335e7fb6a870bb35, []int{10}
}

func (m *ProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileRequest.Unmarshal(m, b)
}
func (m *ProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileRequest.Marshal(b, m, deterministic)
}
func (m *ProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileRequest.Merge(m, src)
}
func (m *ProfileRequest) XXX_Size() int {
	return xxx_messageInfo_ProfileRequest.Size(m)
}
func (m *ProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileRequest proto.InternalMessageInfo

func (m *ProfileRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ProfileReply struct {
	Followers            []string `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
	Following            []string `protobuf:"bytes,2,rep,name=following,proto3" json:"following,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileReply) Reset()         { *m = ProfileReply{} }
func (m *ProfileReply) String() string { return proto.CompactTextString(m) }
func (*ProfileReply) ProtoMessage()    {}
func (*ProfileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_335e7fb6a870bb35, []int{11}
}

func (m *ProfileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileReply.Unmarshal(m, b)
}
func (m *ProfileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileReply.Marshal(b, m, deterministic)
}
func (m *ProfileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileReply.Merge(m, src)
}
func (m *ProfileReply) XXX_Size() int {
	return xxx_messageInfo_ProfileReply.Size(m)
}
func (m *ProfileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileReply proto.InternalMessageInfo

func (m *ProfileReply) GetFollowers() []string {
	if m != nil {
		return m.Followers
	}
	return nil
}

func (m *ProfileReply) GetFollowing() []string {
	if m != nil {
		return m.Following
	}
	return nil
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "caw.Timestamp")
	proto.RegisterType((*Caw)(nil), "caw.Caw")
	proto.RegisterType((*RegisteruserRequest)(nil), "caw.RegisteruserRequest")
	proto.RegisterType((*RegisteruserReply)(nil), "caw.RegisteruserReply")
	proto.RegisterType((*CawRequest)(nil), "caw.CawRequest")
	proto.RegisterType((*CawReply)(nil), "caw.CawReply")
	proto.RegisterType((*FollowRequest)(nil), "caw.FollowRequest")
	proto.RegisterType((*FollowReply)(nil), "caw.FollowReply")
	proto.RegisterType((*ReadRequest)(nil), "caw.ReadRequest")
	proto.RegisterType((*ReadReply)(nil), "caw.ReadReply")
	proto.RegisterType((*ProfileRequest)(nil), "caw.ProfileRequest")
	proto.RegisterType((*ProfileReply)(nil), "caw.ProfileReply")
}

func init() { proto.RegisterFile("protos/caw.proto", fileDescriptor_335e7fb6a870bb35) }

var fileDescriptor_335e7fb6a870bb35 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x5f, 0xab, 0xd3, 0x30,
	0x18, 0xc6, 0x69, 0xbb, 0x73, 0x6c, 0xde, 0x9e, 0x33, 0x34, 0x43, 0x28, 0x9b, 0x17, 0x23, 0x88,
	0x4c, 0x18, 0x1b, 0x6e, 0x7a, 0xb1, 0x4b, 0x1d, 0x88, 0xf3, 0x4a, 0x82, 0x37, 0x7a, 0x53, 0xb2,
	0x34, 0xab, 0x81, 0xb6, 0xa9, 0x6d, 0x46, 0xdd, 0xb7, 0xf0, 0x23, 0x4b, 0xd2, 0xb5, 0xb5, 0x20,
	0xb2, 0xbb, 0xf7, 0xef, 0xd3, 0xdf, 0xd3, 0x24, 0xf0, 0xb4, 0x28, 0x95, 0x56, 0xd5, 0x9a, 0xb3,
	0x7a, 0x65, 0x43, 0xec, 0x71, 0x56, 0x93, 0xf7, 0x80, 0xbe, 0xca, 0x4c, 0x54, 0x9a, 0x65, 0x05,
	0x0e, 0xe1, 0x49, 0x25, 0xb8, 0xca, 0xe3, 0x2a, 0x74, 0xe6, 0xce, 0xc2, 0xa3, 0x6d, 0x8a, 0xa7,
	0xe0, 0x9f, 0xdb, 0x96, 0x6b, 0x5b, 0x5d, 0x4e, 0x7e, 0x3b, 0xe0, 0xed, 0x59, 0x7d, 0x9d, 0x29,
	0x73, 0x96, 0x09, 0xbb, 0x8e, 0x68, 0x97, 0x63, 0x0c, 0x23, 0x2d, 0x7e, 0x69, 0xbb, 0x8b, 0xa8,
	0x8d, 0xf1, 0x18, 0x5c, 0x19, 0x87, 0xde, 0xdc, 0x59, 0x3c, 0x50, 0x57, 0xc6, 0x78, 0x06, 0xa8,
	0x60, 0xa5, 0xc8, 0x75, 0x24, 0xe3, 0x70, 0x64, 0xcb, 0x7e, 0x53, 0x38, 0xc4, 0x78, 0x09, 0x48,
	0xb7, 0x9c, 0xe1, 0xdd, 0xdc, 0x59, 0x04, 0x9b, 0xf1, 0xca, 0x78, 0xe9, 0xe8, 0x69, 0x3f, 0x40,
	0xde, 0xc0, 0x84, 0x8a, 0x44, 0x56, 0x5a, 0x94, 0x06, 0x81, 0x8a, 0x9f, 0x67, 0x51, 0xe9, 0xff,
	0x11, 0x92, 0x09, 0x3c, 0x1b, 0xae, 0x14, 0xe9, 0x85, 0x7c, 0x03, 0xd8, 0xb3, 0xfa, 0x86, 0xf5,
	0x7f, 0x1a, 0x1c, 0x18, 0xf2, 0x86, 0x86, 0xc8, 0x2b, 0xf0, 0xad, 0x74, 0x91, 0x5e, 0xf0, 0x14,
	0xcc, 0x59, 0x58, 0xcd, 0x60, 0xe3, 0x5b, 0x5b, 0xa6, 0x67, 0x0f, 0xe8, 0x13, 0x3c, 0x7e, 0x54,
	0x69, 0xaa, 0x6e, 0xa2, 0x98, 0x01, 0xd2, 0x2a, 0x3a, 0xd9, 0xf9, 0x2b, 0x8a, 0xaf, 0x55, 0xb3,
	0x4f, 0x1e, 0x21, 0x68, 0x95, 0x8c, 0xb7, 0x97, 0x10, 0x50, 0xc1, 0xe2, 0x56, 0xf6, 0x39, 0xdc,
	0x73, 0x56, 0x1b, 0x52, 0xc7, 0x92, 0xde, 0x71, 0x56, 0x1f, 0x62, 0xf2, 0x1a, 0x50, 0x33, 0x65,
	0x38, 0x5f, 0xc0, 0x88, 0xb3, 0xda, 0x5c, 0x0e, 0x6f, 0x00, 0x6a, 0xab, 0x64, 0x09, 0xe3, 0x2f,
	0xa5, 0x3a, 0xc9, 0x54, 0xdc, 0xf2, 0xbf, 0x3f, 0xc3, 0x43, 0x37, 0xdd, 0x68, 0xa3, 0x86, 0x5b,
	0x94, 0xcd, 0x07, 0x10, 0xed, 0x0b, 0x7d, 0x57, 0xe6, 0x49, 0xe8, 0xfe, 0xdd, 0x95, 0x79, 0xf2,
	0xe1, 0xdd, 0xf7, 0x6d, 0x22, 0xf5, 0x8f, 0xf3, 0x71, 0xc5, 0x55, 0xb6, 0x3e, 0xa5, 0x8a, 0xe5,
	0x6b, 0x5e, 0x71, 0xf9, 0x76, 0xb7, 0x8b, 0x9a, 0xec, 0x7a, 0xf9, 0x13, 0x15, 0xf5, 0xcf, 0xe0,
	0x78, 0x6f, 0xe3, 0xed, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0x6b, 0x7d, 0x69, 0x1b, 0x03,
	0x00, 0x00,
}
